friend_pages:
  - link: http://gh.fyz666.xyz/link/
    info_selectors:
      item: .flink-list-item
      name:
        selector: .flink-item-name
      link:
        selector: a
        attr: href
      avatar:
        selector: .flink-item-icon img
        attr: data-lazy-src
      feed:
        selector: .flink-item-feed


max_posts_per_friend: 20
OUTDATE_CLEAN: 2000

db: data.db
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
